GET https://database-api-rezeodju2q-et.a.run.app
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyZjAwMGVlZi0wMzQ1LTExZWUtYTI0NS03YzU3NTgxZGZiY2YiLCJuYW1lIjoidWRpbiIsImlhdCI6MTY4NjU1NjY0OCwiZXhwIjoxNjg5MTQ4NjQ4fQ.sYRTB_Bxfmnw3DAJ-743m5Znb4GT4ggVcQMd6QAa_GE

###Login Route
POST https://database-api-rezeodju2q-et.a.run.app/auth/login
Content-Type: application/json

{
  "email": "udina@gmail.com",
  "password": "123456"
}


###Register Route
POST https://database-api-rezeodju2q-et.a.run.app/auth/register
Content-Type: application/json

{
  "name": "mail",
  "email": "mailb@gmail.com",
  "password": "123456",
  "password2": "123456"
}

###Refresh token Route
POST https://database-api-rezeodju2q-et.a.run.app/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODYxMTUyMjcsImV4cCI6MTcxNzY3MjgyNywiaXNzIjoidGVzdC5jb20ifQ.jSfQyfhneG9jOdW-NkTJozOdfdC6iyNUhzlTzjkQeho"
}

###Logout Route
post https://database-api-rezeodju2q-et.a.run.app/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODYxMTUwOTUsImV4cCI6MTY4ODcwNzA5NX0.cac9yS26nEXOT-BXHm2mQ5fiClg6ulERHCzb8sEDNNE

### get id
get https://database-api-rezeodju2q-et.a.run.app/auth/id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMzU4ZDUyOS0wNGZjLTExZWUtOGNhNi03YzU3NTgxZGZiY2YiLCJuYW1lIjoidWRpbjEiLCJpYXQiOjE2ODYxODg1OTMsImV4cCI6MTY4ODc4MDU5M30.Rxw5WwK44qb4TtsORW1o4LVujGHgwxt4VmFgF4MOwW0

### upload user profile data
POST https://database-api-rezeodju2q-et.a.run.app/profil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyZjAwMGVlZi0wMzQ1LTExZWUtYTI0NS03YzU3NTgxZGZiY2YiLCJuYW1lIjoidWRpbiIsImlhdCI6MTY4NjE4ODkzMywiZXhwIjoxNjg4NzgwOTMzfQ.wgdJnjud0G6iVMmMaxk-NSPhYHTzkvME7llHmi9Y62s
Content-Type: application/json

{
  "height": 170,
  "weight": 65,
  "age": 35,
  "gender": "1"
}

### update user profile data
PUT https://database-api-rezeodju2q-et.a.run.app/profil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyZjAwMGVlZi0wMzQ1LTExZWUtYTI0NS03YzU3NTgxZGZiY2YiLCJuYW1lIjoidWRpbiIsImlhdCI6MTY4NjE4ODkzMywiZXhwIjoxNjg4NzgwOTMzfQ.wgdJnjud0G6iVMmMaxk-NSPhYHTzkvME7llHmi9Y62s
Content-Type: application/json

{
  "height": 160,
  "weight": 55,
  "age": 35,
  "gender": "1"
}

### getting user profile data
GET https://database-api-rezeodju2q-et.a.run.app/profil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyZjAwMGVlZi0wMzQ1LTExZWUtYTI0NS03YzU3NTgxZGZiY2YiLCJuYW1lIjoidWRpbiIsImlhdCI6MTY4NjE4ODkzMywiZXhwIjoxNjg4NzgwOTMzfQ.wgdJnjud0G6iVMmMaxk-NSPhYHTzkvME7llHmi9Y62s

### getting user profile data
get https://fastapi-model-ml-rezeodju2q-et.a.run.app