GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMzU4ZDUyOS0wNGZjLTExZWUtOGNhNi03YzU3NTgxZGZiY2YiLCJuYW1lIjoidWRpbjEiLCJpYXQiOjE2ODYxODg1OTMsImV4cCI6MTY4ODc4MDU5M30.Rxw5WwK44qb4TtsORW1o4LVujGHgwxt4VmFgF4MOwW0

###Login Route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "udina@gmail.com",
  "password": "123456"
}


###Register Route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "udin1",
  "email": "udinajaib@gmail.com",
  "password": "123456",
  "password2": "123456"
}

###Refresh token Route
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODYxMTUyMjcsImV4cCI6MTcxNzY3MjgyNywiaXNzIjoidGVzdC5jb20ifQ.jSfQyfhneG9jOdW-NkTJozOdfdC6iyNUhzlTzjkQeho"
}

###Logout Route
post http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODYxMTUwOTUsImV4cCI6MTY4ODcwNzA5NX0.cac9yS26nEXOT-BXHm2mQ5fiClg6ulERHCzb8sEDNNE

### get id
get http://localhost:3000/auth/id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMzU4ZDUyOS0wNGZjLTExZWUtOGNhNi03YzU3NTgxZGZiY2YiLCJuYW1lIjoidWRpbjEiLCJpYXQiOjE2ODYxODg1OTMsImV4cCI6MTY4ODc4MDU5M30.Rxw5WwK44qb4TtsORW1o4LVujGHgwxt4VmFgF4MOwW0

### upload user profile data
POST http://localhost:3000/profil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyZjAwMGVlZi0wMzQ1LTExZWUtYTI0NS03YzU3NTgxZGZiY2YiLCJuYW1lIjoidWRpbiIsImlhdCI6MTY4NjE4ODkzMywiZXhwIjoxNjg4NzgwOTMzfQ.wgdJnjud0G6iVMmMaxk-NSPhYHTzkvME7llHmi9Y62s
Content-Type: application/json

{
  "height": 170,
  "weight": 65,
  "age": 35,
  "gender": "1"
}

### update user profile data
PUT http://localhost:3000/profil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyZjAwMGVlZi0wMzQ1LTExZWUtYTI0NS03YzU3NTgxZGZiY2YiLCJuYW1lIjoidWRpbiIsImlhdCI6MTY4NjE4ODkzMywiZXhwIjoxNjg4NzgwOTMzfQ.wgdJnjud0G6iVMmMaxk-NSPhYHTzkvME7llHmi9Y62s
Content-Type: application/json

{
  "height": 160,
  "weight": 55,
  "age": 35,
  "gender": "1"
}

### getting user profile data
GET http://localhost:3000/profil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyZjAwMGVlZi0wMzQ1LTExZWUtYTI0NS03YzU3NTgxZGZiY2YiLCJuYW1lIjoidWRpbiIsImlhdCI6MTY4NjE4ODkzMywiZXhwIjoxNjg4NzgwOTMzfQ.wgdJnjud0G6iVMmMaxk-NSPhYHTzkvME7llHmi9Y62s